export type RealEstateHeaderBottomType = {
    continent: string;
    countries: string[];
};

export const categoryData: RealEstateHeaderBottomType[] = [
    {
        continent: "Asia",
        countries: [
            "Afghanistan",
            "China",
            "Cambodia",
            "Japan",
            "Indonesia",
            "Pakistan",
            "India",
            "Bangladesh",
            "Vietnam",
            "Thailand",
            "Philippines",
            "South Korea",
            "Iran",
            "Qatar",
            "Oman",
            "Kuwait",
            "Saudi Arabia",
            "Turkey",
            "Iraq",
            "Uzbekistan",
            "Yemen",
        ],
    },
    {
        continent: "Africa",
        countries: [
            "Nigeria",
            "Ethiopia",
            "Egypt",
            "South Africa",
            "Kenya",
            "Uganda",
            "Tanzania",
            "Algeria",
            "Sudan",
            "Morocco",
            "Angola",
            "Ghana",
            "Mozambique",
            "Madagascar",
            "Cameroon",
        ],
    },
    {
        continent: "North America",
        countries: [
            "United States",
            "Canada",
            "Mexico",
            "Guatemala",
            "Honduras",
            "El Salvador",
            "Cuba",
            "Jamaica",
            "Dominican Republic",
            "Costa Rica",
        ],
    },
    {
        continent: "South America",
        countries: [
            "Brazil",
            "Argentina",
            "Colombia",
            "Peru",
            "Venezuela",
            "Chile",
            "Ecuador",
            "Bolivia",
            "Paraguay",
            "Uruguay",
        ],
    },
    {
        continent: "Europe",
        countries: [
            "Germany",
            "United Kingdom",
            "France",
            "Italy",
            "Spain",
            "Netherlands",
            "Belgium",
            "Sweden",
            "Norway",
            "Finland",
            "Poland",
            "Austria",
            "Switzerland",
            "Portugal",
            "Denmark",
        ],
    },
    {
        continent: "Australia",
        countries: [
            "Australia",
            "New Zealand",
            "Papua New Guinea",
            "Fiji",
            "Solomon Islands",
            "Vanuatu",
            "Samoa",
            "Kiribati",
            "Tonga",
            "Micronesia",
        ],
    },
    {
        continent: "",
        countries: [],
    },
];
