export const carFeaturedProducts = [
    {
        image: "/images/categories/car/featured-products/car-featured-products-1.png",
        name: "Audi A5 – 2023",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "155 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$50,000",
        greatPrice: true,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-2.png",
        name: "Audi A4 – 2022",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "150 mph",
        fuelType: "Diseal",
        transmission: "Manual",
        price: "$120,000",
        greatPrice: true,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-3.png",
        name: "Audi A3 – 2021",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "145 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$20,000",
        greatPrice: false,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-4.png",
        name: "Toyota Camry New",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "145 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$120,000",
        greatPrice: false,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-1.png",
        name: "Audi A5 – 2023",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "155 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$50,000",
        greatPrice: true,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-2.png",
        name: "Audi A4 – 2022",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "150 mph",
        fuelType: "Diseal",
        transmission: "Manual",
        price: "$120,000",
        greatPrice: true,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-3.png",
        name: "Audi A3 – 2021",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "145 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$20,000",
        greatPrice: false,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-4.png",
        name: "Toyota Camry New",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "145 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$120,000",
        greatPrice: false,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-1.png",
        name: "Audi A5 – 2023",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "155 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$50,000",
        greatPrice: true,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-2.png",
        name: "Audi A4 – 2022",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "150 mph",
        fuelType: "Diseal",
        transmission: "Manual",
        price: "$120,000",
        greatPrice: true,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-3.png",
        name: "Audi A3 – 2021",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "145 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$20,000",
        greatPrice: false,
        link: "#",
    },
    {
        image: "/images/categories/car/featured-products/car-featured-products-4.png",
        name: "Toyota Camry New",
        description: "2.0 D5 PowerPulse Momentum 5dr AWD…",
        topSpeed: "145 mph",
        fuelType: "Petrol",
        transmission: "Automatic",
        price: "$120,000",
        greatPrice: false,
        link: "#",
    },
];
