name: React App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Clear npm cache and install dependencies
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm cache clean --force
          npm install

      - name: Build the React app
        run: npm run build

      - name: Create .ssh directory
        run: mkdir -p /home/runner/.ssh

      - name: Create PEM file
        run: echo "${{ secrets.EC2_PEM_KEY }}" > /home/runner/.ssh/key.pem

      - name: Set PEM file permissions
        run: chmod 600 /home/runner/.ssh/key.pem

      - name: Deploy React app to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/key.pem -r dist/ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/ReactApp
          ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            cd /home/ubuntu/ReactApp
            pm2 reload ReactApp || pm2 start ReactApp
          EOF
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      - name: Clean up PEM file
        run: rm /home/runner/.ssh/key.pem